# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb1c9fed7557fa96ab77c06244be17eae63f0987ee482d8cb993af7356daaccb1088716ea98305c14947c57330938c818b73cb4ff50c2957b0a9332de5bb3e0e

test:
  secret_key_base: f954e5650069d94696e8a838feaf53a40ddb63de5674e147ba7389bd6747ae33ce2290ff9221689871a1e9c41671ffa569bcd96454bd73c364f9df42c74febdb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
